# Generated by Django 4.1.1 on 2022-10-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutosNuevo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=30)),
                ("modelo", models.CharField(max_length=30)),
                ("version", models.CharField(max_length=30)),
                ("fecha_de_fabricacion", models.DateField(null=True)),
                ("color", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="AutosUsado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=30)),
                ("modelo", models.CharField(max_length=30)),
                ("version", models.CharField(max_length=30)),
                ("color", models.CharField(max_length=30)),
                ("fecha_de_fabricacion", models.DateField(null=True)),
                ("fecha_de_patentacion", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MotosNueva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=30)),
                ("modelo", models.CharField(max_length=30)),
                ("cilindrada", models.CharField(max_length=30)),
                ("color", models.CharField(max_length=30)),
                ("fecha_de_fabricacion", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MotosUsada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=30)),
                ("modelo", models.CharField(max_length=30)),
                ("cilindrada", models.CharField(max_length=30)),
                ("color", models.CharField(max_length=30)),
                ("fecha_de_fabricacion", models.DateField(null=True)),
                ("fecha_de_patentacion", models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Articulo",
        ),
        migrations.DeleteModel(
            name="Autor",
        ),
        migrations.DeleteModel(
            name="Seccion",
        ),
    ]
